import { StyleSheet } from "react-native";
import Config from "../../../config";

export const styles = StyleSheet.create({
  card: {
    flexDirection: "row",
    backgroundColor: Config.COLORS.NEUTRAL.WHITE,
    marginHorizontal: 20,
    marginVertical: 8,
    borderRadius: 18,
    padding: 20,
    shadowColor: Config.COLORS.PRIMARY,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 8,
  },
  imageContainer: {
    position: "relative",
    width: 90,
    height: 90,
    borderRadius: 18,
    overflow: "hidden",
  },
  image: {
    width: "100%",
    height: "100%",
    backgroundColor: Config.COLORS.SPORT.LIGHT,
  },
  imageLoader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Config.COLORS.SPORT.LIGHT,
  },
  imagePlaceholder: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Config.COLORS.PURPLE.LIGHT,
  },
  typeIndicator: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 26,
    height: 26,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: Config.COLORS.SHADOW,
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 2,
  },
  infoContainer: {
    flex: 1,
    marginLeft: 16,
    justifyContent: "space-between",
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  name: {
    flex: 1,
    fontSize: 17,
    fontWeight: "700",
    color: "#2D3748",
    marginRight: 8,
    letterSpacing: -0.2,
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Config.COLORS.NEUTRAL.LIGHT,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
  },
  rating: {
    fontSize: 13,
    fontWeight: "600",
    color: Config.COLORS.NEUTRAL.DARK_GRAY,
    marginLeft: 3,
  },
  address: {
    fontSize: 14,
    color: Config.COLORS.NEUTRAL.GRAY,
    lineHeight: 18,
    marginBottom: 8,
  },
  detailsRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: 4,
  },
  distanceContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 12,
    marginBottom: 4,
  },
  distance: {
    fontSize: 12,
    color: Config.COLORS.NEUTRAL.GRAY,
    marginLeft: 2,
  },
  statusContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 12,
    marginBottom: 4,
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    marginRight: 4,
  },
  statusText: {
    fontSize: 12,
    fontWeight: "500",
  },
  priceLevelContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  priceSymbol: {
    fontSize: 12,
    fontWeight: "bold",
  },
  venueType: {
    fontSize: 12,
    color: Config.COLORS.PURPLE.DARK,
    fontWeight: "500",
  },
  arrowContainer: {
    justifyContent: "center",
    alignItems: "center",
    width: 20,
  },
});
