import { StyleSheet } from "react-native";
import Config from "../../../config";

export const styles = StyleSheet.create({
  container: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 16,
    borderWidth: 1.5,
    paddingHorizontal: 14,
    height: 56,
    shadowColor: Config.COLORS.PRIMARY,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  bottomSearchButton: {
    marginTop: 10,
    alignItems: "center",
    backgroundColor: Config.COLORS.PRIMARY,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    shadowColor: Config.COLORS.PRIMARY,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
  },
  bottomSearchText: {
    color: Config.COLORS.NEUTRAL.WHITE,
    fontSize: 16,
    fontWeight: "600",
  },
  autocompleteContainer: {
    marginTop: 8,
    backgroundColor: Config.COLORS.SPORT.WHITE,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Config.COLORS.SPORT.GRAY,
    shadowColor: Config.COLORS.PRIMARY,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
    maxHeight: 200,
    overflow: "hidden",
  },
  autocompleteItem: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: Config.COLORS.NEUTRAL.LIGHT,
  },
  autocompleteText: {
    fontSize: 14,
    color: Config.COLORS.SPORT.DARK,
  },
  predictionsFooter: { paddingVertical: 10, alignItems: "center" },
  iconContainer: {
    marginRight: 8,
  },
  input: {
    flex: 1,
    fontSize: 17,
    color: Config.COLORS.SPORT.DARK,
    paddingVertical: 12,
    paddingHorizontal: 0,
    fontWeight: "500",
    letterSpacing: 0.2,
  },
  loadingContainer: {
    marginLeft: 8,
    backgroundColor: Config.COLORS.NEUTRAL.LIGHT,
    borderRadius: 10,
    padding: 8,
  },
  searchButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
    backgroundColor: Config.COLORS.PRIMARY,
    shadowColor: Config.COLORS.PRIMARY,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  locationActiveButton: {
    backgroundColor: Config.COLORS.PRIMARY,
  },
  locationIdleButton: {
    backgroundColor: Config.COLORS.NEUTRAL.LIGHT_GRAY,
  },
});
