import { StyleSheet } from "react-native";
import Config from "../../../config";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  header: {
    paddingHorizontal: 24,
    paddingTop: 40,
    paddingBottom: 32,
    backgroundColor: Config.COLORS.PRIMARY,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: "#6A4C93",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 12,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: "800",
    color: Config.COLORS.SPORT.WHITE,
    marginBottom: 8,
    textAlign: "center",
    letterSpacing: -0.5,
  },
  headerSubtitle: {
    fontSize: 17,
    color: "rgba(255, 255, 255, 0.8)",
    textAlign: "center",
    fontWeight: "400",
    letterSpacing: 0.2,
  },
  searchSection: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: Config.COLORS.SPORT.WHITE,
    borderRadius: 20,
    marginHorizontal: 20,
    marginTop: -8,
    shadowColor: "#6A4C93",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 8,
  },
  resultsSection: {
    flex: 1,
    paddingTop: 8,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 100,
  },
  loadingText: {
    marginTop: 15,
    fontSize: 18,
    color: Config.COLORS.PRIMARY,
    fontWeight: "500",
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
    backgroundColor: Config.COLORS.SPORT.WHITE,
    marginHorizontal: 20,
    marginTop: 24,
    borderRadius: 20,
    shadowColor: "#6A4C93",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 6,
  },
  emptyText: {
    fontSize: 22,
    fontWeight: "700",
    color: Config.COLORS.PRIMARY,
    textAlign: "center",
    marginBottom: 16,
    letterSpacing: -0.3,
  },
  emptySubtext: {
    fontSize: 16,
    color: "#64748B",
    textAlign: "center",
    lineHeight: 24,
    fontWeight: "400",
    letterSpacing: 0.1,
  },
});
